### ISSUE TITLE
Formular scheint nicht mehr zu gehen....

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#100]
Bin gerade zufällig auf eine Seite gestoßen, die scheinbar nicht mehr geht. Hier ist ein Formular hinterlegt, dass aber scheinbar nicht mehr geht:

https://www.fuerthwiki.de/wiki/index.php/Liste_aller_Stra%C3%9Fen,_Pl%C3%A4tze_und_Anlagen

**Comment by markmuzenhardt** [comment]
Funktioniert wieder.
