### ISSUE TITLE
Suchfeld in der mobilen Version "optimieren"

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#108]
Ergebnis aus der gemeinsamen Besprechung in der Freibank:
In der moblien Fassung ist das Suchfeld bei uns nur schwer erkennbar. Im Vergleich zur Wikipedia sieht man das "Problem". Wikipedia hat das Feld grau unterlegt und dort nochmal einen "Home-Button" hinterlegt. Evtl könnte man bei uns auch das Feld farblich unterlegen (grün?) - und den Home-Button integrieren?

![scr mob 3](https://user-images.githubusercontent.com/31972645/43578617-931d63c6-964f-11e8-9000-da46e4d20b6e.jpg)

**Comment by mojoaxel** [comment]
Gute Idee! Ich setze das mal auf meine ToDo Liste :wink:

**Comment by mojoaxel** [comment]
Ich hab das jetzt mal so hier umgesetzt:
![image](https://user-images.githubusercontent.com/600565/46626717-779a2d00-cb38-11e8-8f78-9a5feb9e6937.png)
