### ISSUE TITLE
Bild-Kategorien erweitern

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#112]
Bisher kann man bei Bildern bis zu drei Kategorien / Attribute auswählen. Innerhalb des HTML Textes kann ich auch mehr anlengen, allerdings liest er diese nicht mehr für die Artikel aus. Allerdings haben wir immer wieder mal Bilder, die eigentlich mehr Attribute/ Kategorien als drei Stück bräuchten - weil z.B. ein Gebäude zu sehen ist, in dem eine Firma ist, dessen Architekt wir aber auch noch darstellen wollen etc. etc. Deshalb wäre es sinnvoll, dass wir die Anzahl der Kategorien mittel- bis langfristig mal erweitern auf mind. 4 bzw. 5 Kategorien. 

Beispiel:
{{Bild
|Genre=Buchseiten; Historische Bilder
|Attribut=Gebäude
|Wert=Bambergisches Amtshaus
|Attribut2=Firma
|Wert2=Architekturbüro Peringer und Rogler
|Attribut3=Buch
|Wert3=Die Stadt Fürth in Bayern (Buch)
|Quellangaben=[[FürthWiki e. V.#Archiv FürthWiki e. V.|Archiv FürthWiki e. V.]]
|Straße=Gustavstraße
|Hausnummer=65
|über Datum=1907
|Lizenz=cc-by-sa-3.0
|Beschreibung=Altes Rentamt, Gustavstr. 65, Aufnahme um 1907
}}

**Comment by markmuzenhardt** [comment]
Done.
