### ISSUE TITLE
Mobilmachung: Time-Slider

### ISSUE THREAD

**Issue by mojoaxel** [fuerthwiki/wiki#117]
@zonebattler schreibt:
> Die Sliderfotos sind in der Mobilfassung auf dem Smartphone leider nur ruckartig mit Tippen zu bewegen, nicht jedoch mit kontinuierlichem Zeigefinger-Wischen. In WordPress geht's aber, siehe https://www.klein-aber-fein.de/labor/pruefstand/
Vermutlich liegt das an einer aktuelleren Skriptversion des entsprechenden Plugins, siehe https://de.wordpress.org/plugins/twenty20/
Könnte das bitte einer von Euch beiden Admins im FürthWiki-Maschinenraum gelegentlich updaten? Wäre schick, danke!

**Comment by mojoaxel** [comment]
Ich hab mir das mal angeschaut und das [Widget:Twentytwenty](https://www.fuerthwiki.de/wiki/index.php/Widget:Twentytwenty) upgedated.
Scheint Alles auch nach meine Update in der klassischen Ansicht auch weiterhin problemlos zu funktionieren.

Leider gibt es aber bei mit der Mobilen Ansicht weiter Probleme. So wie es aussieht wird im mobilen Kontext das Javascript nicht mehr ausgeführt. **Problem besteht weiterhin** :cry:

**Comment by mojoaxel** [comment]
@zonebattler :tada: Hab den Fehler gefunden. Jetzt sollte Alles wieder gehn!

**Comment by zonebattler** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Du untertreibst, mein Lieber: es geht jetzt erstmals richtig, also mit Ziehen statt nur sprunghaft mit Tippen! Klasse! Dickes Dankeschön!

Beste Grüße,Ralph Stenzel
-- 0911 - 74 33 802 (drinnen)0177 - 19 55 099 (draußen)
https://www.zonebattler.nethttps://www.fuerther-freiheit.infohttps://www.trifolia.net
 

Alexander Wunschik schrieb am 01.08.2019 13:27:

@zonebattler 🎉 Hab den Fehler gefunden. Jetzt sollte Alles wieder gehn!
