### ISSUE TITLE
Kommentarfeld bei "Text ersetzen"-Funktion

### ISSUE THREAD

**Issue by mojoaxel** [fuerthwiki/wiki#14]
Originally reported by: **Günter Scheuerer (Bitbucket: [DocBendit](https://bitbucket.org/DocBendit), GitHub: Unknown)**

----------------------------------------

Bei der sehr wichtigen und mächtigen Funktion "Text ersetzen" ist ein Kommentarfeld wünschenswert um jede angestoßene Aktion beschreiben zu können.

----------------------------------------
- Bitbucket: https://bitbucket.org/FuerthWiki/wiki/issue/14

**Comment by markmuzenhardt** [comment]
Der Kommentar wird durch die Erweiterung selbst beschrieben. Leider ist es ein zu großer Eingriff in die Erweiterung, diese Funktion gezielt einzupflegen, sonst müssten wir diese Funktion mit jedem Update wieder neu einbauen. Weil in absehbarer Zeit nicht mit vertretbarem Aufwand durchführbar, erlaube ich mir das Ticket zu schließen.

**Comment by mojoaxel** [comment]
Schön wäre das. Ich halte das auch für einen zu großen Aufwand.
