### ISSUE TITLE
Bild-Kategorisierungs-Auswahlliste fehlt

### ISSUE THREAD

**Issue by mojoaxel** [fuerthwiki/wiki#23]
Originally reported by: **Kamran  Salimi (Bitbucket: [Kasa_Fue](https://bitbucket.org/Kasa_Fue), GitHub: Unknown)**

----------------------------------------

Beim Upload von Bilder konnte man bisher mittels "Hacken-setzen" sagen, was das für Bild ist, z.B. Postkarte, Plan, Titelseite, Historisches Bild, Luftbild, Portrait etc. .. Diese Auswahlliste ist nicht mehr da, so dass man nun per Hand eingeben muss was es sein soll - jetzt steht nur noch "Genre" da, und in das Freitextfeld muss man per Hand eingeben um was es sich handelt. Das birgt viele Fehler, von daher wäre die "alte" Auswahlliste sicherlich wieder zielführend. ![Auswahlliste ist weg.JPG](https://bitbucket.org/repo/aEd5XE/images/552977138-Auswahlliste%20ist%20weg.JPG)

----------------------------------------
- Bitbucket: https://bitbucket.org/FuerthWiki/wiki/issue/23

**Comment by KasaFue** [comment]
Angesichts der Bedeutung und Wichtigkeit dieses Themas versuche einfach nochmal an das Problem zu erinnern. Das Thema ist seit über einem Viertel Jahr virulent - wir haben inzwischen über 200 neue Bilder in dieser Zeit - und bei den Rechtsanwälten, die auf Abmahnverfahren spezialisiert sind -sollten wir diese Thema bald abschließen, sonst wird´s evtl. teuer für uns.

**Comment by markmuzenhardt** [comment]
Lizenzvorlage sind nun wieder auswählbar.
