### ISSUE TITLE
Sortierung innerhalb von Tabellen

### ISSUE THREAD

**Issue by mojoaxel** [fuerthwiki/wiki#33]
Originally reported by: **Kamran  Salimi (Bitbucket: [Kasa_Fue](https://bitbucket.org/Kasa_Fue), GitHub: Unknown)**

----------------------------------------

Die Sortierung innerhalb von Tabellen macht häufig keinen Sinn, so werden z.B. die Personen innerhalb einer Tabelle alphabetisch nach Vornamen statt nach Namen sortiert, wie hier z.B. 

https://www.fuerthwiki.de/wiki/index.php?title=Christlich-Soziale_Union#Pers.C3.B6nlichkeiten 

oder bei Datumsangaben wird die Jahreszahl mit dem Tag/Monat durcheinander geworfen in der Darstellung, so dass unsinnige Darstellungen entstehen: 

https://www.fuerthwiki.de/wiki/index.php?title=Bundesverdienstkreuz 

-> hier z.B. 4. Februar kommt nach 2016, weil die 4 vom Tag natürlich "höher" ist als die 2 von 2016 etc.. 

Seht ihr eine Chance das Problem der Darstellung zu lösen. Es ist kein Bug durch die das neue Update, das Problem hatten wir auch schon vorher.

----------------------------------------
- Bitbucket: https://bitbucket.org/FuerthWiki/wiki/issue/33

**Comment by markmuzenhardt** [comment]
Sortierung innerhalb von Tabellen funktioniert jetzt, muss aber bei den einzelnen Tabellen erst eingerichtet werden. Man muss hier unter die Lupe nehmen, für welche Tabellen das überhaupt ein Problem ist...

**Comment by markmuzenhardt** [comment]
Problem gelöst, muss aber bei so mancher Tabelle noch nach moderner Machart eingefügt werden.

**Comment by mojoaxel** [comment]
:tada:
