### ISSUE TITLE
Verwerfen von Daten bei Benutzung des Bildformulars

### ISSUE THREAD

**Issue by mojoaxel** [fuerthwiki/wiki#35]
Originally reported by: **Günter Scheuerer (Bitbucket: [DocBendit](https://bitbucket.org/DocBendit), GitHub: Unknown)**

----------------------------------------

Werden an einer vorhandenen Datei Änderungen mittels Formular eingegeben und abgespeichert werden vorher manuell über die "Bearbeiten"-Funktion eingegebene Daten die nicht in einem Formularfeld stehen verworfen. Das ist einerseits logisch, weil das Formular natürlich nur seinen eigenen Inhalt abbildet aber andererseits höchst ärgerlich da so immer wieder Informationen verloren gehen. Evtl. müsste man die manuelle Bearbeitung von Dateibeschreibungen unterbinden?! Beispiel siehe letzten Edit von Datei:Martersäule Rückseite.jpg

----------------------------------------
- Bitbucket: https://bitbucket.org/FuerthWiki/wiki/issue/35

**Comment by markmuzenhardt** [comment]
Was wird denn hier verworfen? Die manuelle Bearbeitung ermöglicht doch beliebigen Text zu einem Bild hinzuzufügen, ohne dass bei der Bearbeitung mit dem Formular etwas verloren geht.

**Comment by markmuzenhardt** [comment]
Das kann nur umgangen werden, indem die nicht durch das Formular zu ersetzenden Daten (wie z. B. Zusatz-Kategorien) in den Artikel eingetragen werden und nicht in das Formular. Bei bestehenden Bildern sollte man hier etwas aufpassen, da es keine mögliche Automatik gibt, um das zu verhindern.
