### ISSUE TITLE
Vergrößern von Bildern

### ISSUE THREAD

**Issue by mojoaxel** [fuerthwiki/wiki#38]
Originally reported by: **Günter Scheuerer (Bitbucket: [DocBendit](https://bitbucket.org/DocBendit), GitHub: Unknown)**

----------------------------------------

Ist derzeit relativ umständlich. Da wir Bilder jetzt auch in höherer Auflösung hochladen dürfen besteht nun vermehrt die Möglichkeit das Bild durch anklicken noch vergrößert anzeigen zu lassen. Allerdings sind dazu derzeit vier! Schritte nötig auf die Otto-Normal-Nutzer kaum kommt. Bilder sagen ja bekanntlich mehr als Worte und deshalb sollte hier  dringend eine Möglichkeit geschaffen werden das zu vereinfachen. 

Beispiel: Auflösung Monatsrätsel Juli, Bilddatei Datei:Karolinenstraße 42.jpg

Schritt 1: Bild im Artikel anklicken (erzeugt das Vorschau-Bild)

Schritt 2: bei der Bildunterschrift des Vorschaubildes auf 'Details' klicken (damit kommt man zur Dateiseite samt Bildbeschreibung)

Schritt 3: Bild nochmals anklicken (führt zur direkten URL des Bildes)

Schritt 4: Bild nochmals anklicken (erzeugt Zoom, wodurch Sinn des Bildes erst klar wird)

----------------------------------------
- Bitbucket: https://bitbucket.org/FuerthWiki/wiki/issue/38

**Comment by markmuzenhardt** [comment]
Die Möglichkeit gibt's schon: 

- Rechtsklick auf Bild => "Bild in neuem Tab öffnen" 
- Klick auf "Originaldatei"
