### ISSUE TITLE
Liste "Landtagsabgeordneter" unvollständig

### ISSUE THREAD

**Issue by mojoaxel** [fuerthwiki/wiki#39]
Originally reported by: **Alexander Wunschik (Bitbucket: [mojoaxel](https://bitbucket.org/mojoaxel), GitHub: [mojoaxel](https://github.com/mojoaxel))**

----------------------------------------

Auf der Seite "Landtagsabgeordneter" fehlt z.B. Petra Guttenberger.

----------------------------------------
- Bitbucket: https://bitbucket.org/FuerthWiki/wiki/issue/39

**Comment by markmuzenhardt** [comment]
Wenn die Funktion "Landtagsabgeordneter" zu einer Person hinzugefügt wird, dann erscheint diese im Artikel "Landtagsabgeordneter" mit der Vorlage {{Person mit dieser Funktion}}. Wenn der Beruf "Landtagsabgeordneter" vergeben ist, dann erscheint die Person im Artikel "Landtagsabgeordneter" mit der Vorlage "{{Berufe}}". Eigentlich müsste man das überarbeiten, denn "Landtagsabgeordneter" ist kein Beruf, sondern ein Amt. Der Beruf müsste eigentlich "Politiker" sein und der Artikel "Landtagsabgeordneter" müsste verschwinden, weil die Funktion eigentlich "Mitglied des Bayerischen Landtages" heißen müsste.
