### ISSUE TITLE
eMail und Kontaktdaten

### ISSUE THREAD

**Issue by mojoaxel** [fuerthwiki/wiki#52]
Originally reported by: **Alexander Wunschik (Bitbucket: [mojoaxel](https://bitbucket.org/mojoaxel), GitHub: [mojoaxel](https://github.com/mojoaxel))**

----------------------------------------

Besonders in der Mobilen Ansicht fehlt noch eine Kontaktadresse. Ralph hat sich gewünscht, das die eMail-Adresse zum  Mobilen-Menü hinzugefügt wird, was dank meiner neuen Extension auch kein Problem ist.

Ich möchte Allerdings eine Alternative vorschlagen: Lasst uns doch eine Kontakt-Seite erstellen. Dort können wir dann die eMail Adresse nennen aber auch die Post-Adresse der Vereins und ggf. sogar eine Telefonnummer für dringende Rückfragen. Auch wär es hier möglich für die Technik einen Extra Ansprechpartner zu nennen (z.B. bugs@fuertwiki.de).

Wie wollen wir es machen: Kontaktseite oder einfach eMails-Adresse?

----------------------------------------
- Bitbucket: https://bitbucket.org/FuerthWiki/wiki/issue/52

**Comment by markmuzenhardt** [comment]
Mailadresse im Wiki hatten wir schon. Dauert nicht lange, dann kann man diese Mailadresse wegschmeißen, weil es einem das Postfach mit exponential steigender Junkmail-Frequenz zumüllt. Bitte auf KEINEN Fall die Vorstands- oder Kuratoriums-Adresse im Wiki veröffentlichen (!!!), weil wir auf diese Adressen angewiesen sind.

**Comment by zonebattler** [comment]
Die Adressen sind doch schon seit längerem veröffentlicht, auf den weiter oben genannten Impressums-Seiten ebenso wie auf

http://www.fuerthwiki.de/verein/verein/vorstand/

und

http://www.fuerthwiki.de/verein/verein/kuratorium/

Hat zumindest bis dato nicht zu Spam-Bombardement geführt...

**Comment by mojoaxel** [comment]
eMail ist jetzt im Mobilen Menü als "Kontakt" enthalten .
