### ISSUE TITLE
Fehler bei der Anmeldung

### ISSUE THREAD

**Issue by mojoaxel** [fuerthwiki/wiki#56]
Im moment ist es leider nicht möglich sich anzumelden!!!! 
Vermutlich bereits seit ca. 2 Wochen :-(

@markmuzenhardt Wir müssen das sofort fixen!

```
Hallo,

jemand mit der IP-Adresse 188.193.200.240, wahrscheinlich du selbst, hat das Benutzerkonto „Testuser“ bei FürthWiki registriert.

Um die E-Mail-Funktionen von FürthWiki (wieder) zu aktivieren und um zu bestätigen,
dass dieses Benutzerkonto wirklich zu deiner E-Mail-Adresse und damit zu dir gehört, öffne bitte folgenden Link in deinem Browser:

https:///$SECRET_wgServer/wiki/index.php/Special:ConfirmEmail/fa91c3079095635493691642d53c51ce85ec6

Wenn du das genannte Benutzerkonto *nicht* registriert hast, folge diesem Link, um den Bestätigungsprozess abzubrechen:

https:///$SECRET_wgServer/wiki/index.php/Special:InvalidateEmail/fa91c30790934543593691642d53c51ce85ec6

Dieser Bestätigungscode ist gültig bis zum 21. September 2017, 15:06 Uhr.
```

**Comment by markmuzenhardt** [comment]
Das Problem war in die CanonicalURL, welche von mir wegen des https-Problems mit dem Hauptseiten-Bild in die LocalSettings.php eingetragen wurde. Php hat wirklich einen grausamen Parser der Variablen in Strings mal auflöst und mal nicht. Naja, Problem trotzdem gelöst.

**Comment by mojoaxel** [comment]
🎉  Danke!
Habs auch gerade gesehn. Das Problem ist durch f01eec04bc504a57b7bbd9e18949cd41f6396fa9 gekommen und zum Glück also ERST 3 Tage alt!
