### ISSUE TITLE
Aufrufzähler auf Diskussions-Seiten

### ISSUE THREAD

**Issue by mojoaxel** [fuerthwiki/wiki#58]
Günter ist aufgefallen, das der Aufrufzähler für Artikel und deren Diskussions-Seiten immer gleich ist. z.B.:

```Diese Seite wurde bisher 817 mal abgerufen.```

Der Aufrufzähler soll für Diskussions-Seiten entfernt oder berichtigt werden.

**Comment by markmuzenhardt** [comment]
Offenbar werden die Diskussionsseiten nicht mehr gezählt und der Artikelzähler angezeigt. Sollte man mindestens bis Jahresende so laufen lassen und wenn Piwik genügend Daten gesammelt hat sollten wir das in ähnlicher Manier wie die Wikipedia es tut den Nutzern zugänglich machen.

**Comment by mojoaxel** [comment]
Evtl. ist es möglich (z.B. über einen CSS Hack) den Zähler auf den Diskussions-Seiten ganz zu verstecken.

**Comment by KasaFue** [comment]
Ganz ehrlich - ich glaube der Zähler geht überhaupt nicht mehr, egal ob Diskussionsseite etc. Der Zähler geht auf keiner Seite mehr, oder?!

**Comment by mojoaxel** [comment]
Es kann gut sein, das irgendein Update die Zähler wieder zerschossen hat. Wie schon oft gesagt, wenden diese Zähler von MediaWiki nicht mehr unterstützt. Wir haben es zwar mit Hilfe einer Extension geschafft die Werte in die aktuelle Version zu retten aber wenn es hier ernsthafte Probleme geben sollte bleibt wohl nix anderes übrig als den Zähler komplett rauszuschmeißen und nur noch Piwik zu verwenden (so wie MediaWiki es auch empfiehlt). Da gibt es leider nicht viel, dass wir tun können. 😢

**Comment by markmuzenhardt** [comment]
Ich schließe das Ticket, weil der Aufrufzähler nur noch ein mal am Tag die Anzahl der Seitenaufrufe aktualisiert, die Auftrufe der Diskussionsseite gibt es nicht mehr.
