### ISSUE TITLE
Zähler auf allen Seiten steht! 

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#59]
Nicht nur auf Diskussionsseiten, sondern generell auf allen Seiten steht der Zähler. Der ging aber schon einmal nach der Umstellung, der "Fehler" muss in den letzten Tagen aufgetreten sein.

**Comment by KasaFue** [comment]
Der Zähler auf den Bild-Seiten scheint noch zu gehen!

**Comment by zonebattler** [comment]
Ich habe die Seite

https://www.fuerthwiki.de/wiki/index.php/Blauer_Kurier_City_Fürth

erst letzten Donnerstag (14.09.2017) erstellt und da scheint der Zähler zu funktionieren (aktuell 19 Aufrufe). Allerdings ist das bislang noch nicht in die Statistik in meiner eigenen Benutzerseite unter

https://www.fuerthwiki.de/wiki/index.php/Benutzer:Zonebattler#Von_Zonebattler_erstellte_Artikel

übernommen worden. Vielleicht ist da nur eine Teilfunktionalität defekt?

**Comment by mojoaxel** [comment]
Ich hab auch das gefühl, das die Zähler nicht mehr richtig funktionieren. Siehe auch:
https://github.com/fuerthwiki/wiki/issues/58#issuecomment-330156853

**Comment by markmuzenhardt** [comment]
Es gibt nur noch einen Zähler für die Artikel, Diskussionsseiten werden nicht mehr gezählt. Die Zähler funktionieren absolut korrekt, da sie nur noch einmal am Tag aktualisiert werden scheint es so, als würde nicht mehr gezählt. Langfristig sollte die Statistik eh über PIWIK abgebildet werden. Schlage aber vor, die alten Seitenzähler noch einige Monate beizubehalten bis PIWIK genügend statistische Informationen gesammelt hat.

**Comment by KasaFue** [comment]
Ahh....danke! Hab mich schon gewundert, warum der Zähler manchmal geht und manchmal nicht ;-)

Danke

Kamran

 

Gesendet: Dienstag, 26. September 2017 um 11:02 Uhr
Von: markmuzenhardt <notifications@github.com>
An: fuerthwiki/wiki <wiki@noreply.github.com>
Cc: KasaFue <info@ka-sa.de>, Author <author@noreply.github.com>
Betreff: Re: [fuerthwiki/wiki] Zähler auf allen Seiten steht! (#59)


Es gibt nur noch einen Zähler für die Artikel, Diskussionsseiten werden nicht mehr gezählt. Die Zähler funktionieren absolut korrekt, da sie nur noch einmal am Tag aktualisiert werden scheint es so, als würde nicht mehr gezählt. Langfristig sollte die Statistik eh über PIWIK abgebildet werden. Schlage aber vor, die alten Seitenzähler noch einige Monate beizubehalten bis PIWIK genügend statistische Informationen gesammelt hat.

**Comment by zonebattler** [comment]
Mir scheint es aber immer noch so zu sein, daß auf meiner Benutzerseite die manuell eingebundenen Zähler für die von mir verfaßten Artikel nicht mehr so tun wie sie sollen. Beispiel unter 

https://www.fuerthwiki.de/wiki/index.php/Benutzer:Zonebattler#Sonstiges

Bei

[[Blauer Kurier City Fürth]] ({{#show:Blauer Kurier City Fürth|?Anzahl der Seitenaufrufe}} Abrufe)

kommt immer noch unverändert "nix" raus....

**Comment by markmuzenhardt** [comment]
Ach so. Das wiederum hat mit den Seitenzählern nix zu tun, das ist ein "SemanticExtraSpecialProperty". Damit der neue Seitenzähler überhaupt über eine semantische Abfrage ({{#show:Blauer Kurier City Fürth|?Anzahl der Seitenaufrufe}}) abgebildet werden kann, war ein Update der besagten "SemanticExtraSpecialProperties"-Extension erforderlich. Gesagt - getan - geht!

**Comment by zonebattler** [comment]
Wow, danke!
