### ISSUE TITLE
Semantik Wiki in Formularen 

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#61]
Bei nicht angelegten Artikeln erscheint in Formularen jetzt nicht mehr z.B. der Name einer Person in rot, also als Hinweis eines nicht existierenden Artikels trotz Verlinkung, sondern jetzt wird der Text in der Tabelle mit den beiden eckigen Klammern angezeigt.  Bsp: https://www.fuerthwiki.de/wiki/index.php/Goldene_B%C3%BCrgermedaille 

![bug semantik formular](https://user-images.githubusercontent.com/31972645/30540614-20d17522-9c78-11e7-9ae4-978e9e974cd2.JPG)

**Comment by KasaFue** [comment]
Zudem Rätselhaft - es gibt schon einen Artikel vom Rassau und Heißmann, trotzdem taucht er einmal "richtig" und einmal "falsch" in der Tabelle auf!

**Comment by KasaFue** [comment]
Der Fehler ist extrem nervig - vielleicht können wir zeitnah eine Lösung finden, denn eine sinnvolle Sortierung ist weder per Name noch per Datum möglich. Beim Namen tauchen viele doppelt auf, und beim Datum kann er nicht zwischen Tag und Jahr unterscheiden. 

![fehler tabelle semantic](https://user-images.githubusercontent.com/31972645/30643279-847af0de-9e0e-11e7-87b9-28eeadad1bca.JPG)

Hier das Beispiel Goldene Bürgermedaille:  https://www.fuerthwiki.de/wiki/index.php/Goldene_B%C3%BCrgermedaille 

Das Problem haben wir aber bei fast allen Tabellenansichten, also nicht nur bei den Auszeichnungen.

**Comment by markmuzenhardt** [comment]
Das lag an der Änderung der Art und Weise, wie semantic MediaWiki mit internen links in Attributen des Datentyps "Zeichenkette" umgeht. Früher hatte ich etwas black-magic eingebaut um das zu ermöglichen, jetzt kann man das als Option einschalten - was gemacht wurde und jetzt also aus dem Karton heraus funktioniert.
