### ISSUE TITLE
Automatisches Logout

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#63]
Irgendwie war ich früher tage bzw. wochenlang eingeloggt, solange ich meinen PC nicht ausgeschaltet habe - was sicher nicht so ok war, aber jetzt muss ich mich schon nach kurzer Zeit wieder einloggen. kann man die automatische Zeit zum ausloggen etwas "verlängern"? Es müssen ja nicht gleich wieder Wochen sein, aber evtl ein paar Stunden ;-)

**Comment by markmuzenhardt** [comment]
Das wird nicht durch das MediaWiki bestimmt, sondern durch `php_value session.gc_maxlifetime 6000` aus der `.htaccess`. Muss mal recherchieren, ob der Eintrag dieses Wertes die gewünschte Verlängerung bringt.

**Comment by markmuzenhardt** [comment]
Haken rein bei "angemeldet bleiben", dann läuft die Session nicht mehr so schnell aus (erst, wenn man zwischendurch von einem anderen Rechner drauf war).
