### ISSUE TITLE
Fehlender Operand?!

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#64]
Was muss man sich unter dieser Fehlermeldung vorsellen?

![fehlermeldung operand](https://user-images.githubusercontent.com/31972645/30643182-296c0d40-9e0e-11e7-9235-1f0c46f12876.JPG)

Link: 
https://www.fuerthwiki.de/wiki/index.php/Rotraut_Grashey

**Comment by KasaFue** [comment]
Das Problem taucht bei fast allen Personen auf, allerdings auch in anderen Formen?! Hilft das weiter?!

![fehlermeldung operand _ 1](https://user-images.githubusercontent.com/31972645/30643390-fcd68b56-9e0e-11e7-8888-9015d6fb2180.JPG)

**Comment by markmuzenhardt** [comment]
Kommt davon, wenn man Plausi-Prüfungen einbaut und die Kandidaten ohne Todesdatum darauf vergleichen möchte, ob ebendas vor dem Geburtsdatum liegt. Nix kann man halt weder mit nix noch mit etwas vergleichen, weil sonst nix raus kommt :-)
