### ISSUE TITLE
VP: PDF lassen sich im Artikel nicht direkt öffnen

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#65]
Wenn man ein PDF hochlädt und in einem Artikel einfügt, dann kann man das PDF im Artikel nicht direkt öffenen. Stattdessen muss man erst die Datei öffnen - und er hier kann dann das PDF geöffnet werden. Beispiel:

![wunsch link im artikel](https://user-images.githubusercontent.com/31972645/30645785-161958e8-9e17-11e7-9d13-f109ab8b8707.JPG)

Im Artikel "Andreas-Winterbauer-Stiftung": https://www.fuerthwiki.de/wiki/index.php/Andreas-Winterbauer-Stiftung 

Hierzu muss man erst auf das Thumbnail des PDF Zeichens gehen - dann auf Details - und wenn jetzt die neue Seite aufgeht, kann man erneut auf das gleiche Thumbnail klicken - und jetzt erst bekomme ich das PDF angezeigt. Sinnvoller wäre es, wenn es gleich im Artikel aufgehen würde - evtl durch eine Verlinkung zu der "eigentlichen" Datei?!

**Comment by markmuzenhardt** [comment]
Done. Jetzt lassen sich PDFs selbst ohne Zusatz-Software direkt auf der Dateiseite anschauen. Das sogar, ohne die Preview-Funktion, die normalerweise bei Bildern erst getriggert wird. Habe die PdfHandler-Extension aktiviert, welche sogar Teil unserer derzeitigen MediaWiki-Version ist.
