### ISSUE TITLE
Wikipedia:Formatvorlage Gastronomie

### ISSUE THREAD

**Issue by mojoaxel** [fuerthwiki/wiki#66]
Auf einigen Seiten gibt es sowohl die _Vorlage:Gebäude_ als auch _Wikipedia:Formatvorlage Gastronomie_.
Diese Sollen wir irgendwie "verheiraten".

Beispiel:
https://fuerthwiki.de/wiki/index.php/Gr%C3%BCner_Baum

**Comment by markmuzenhardt** [comment]
Eigentlich muss man Gaststätten und Gebäude immer strikt trennen. Gibt es ein Gebäude "Grüner Baum" und eine Gaststätte "Grüner Baum", dann sollte man hier unbedingt 2 getrennte Artikel anstreben (also "Grüner Baum" und "Gustavstraße 34". 
Will man trotzdem Informationen über das Gebäude in der Faktenbox der Gaststätte haben, so sollte man das als Reiter einblenden in den Gaststätten-Artikel.

**Comment by markmuzenhardt** [comment]
Da die neue Herangehensweise an Gaststätten das Problem adressiert, schließe ich das Ticket ab. Gebäude und Gaststätten müssen künftig immer getrennte Artikel sein, wenn es gegenwärtig nicht so ist dann muss es geändert werden.
