### ISSUE TITLE
Falsche Datumsangaben durch fehlerhafte PageForms-Extension

### ISSUE THREAD

**Issue by zonebattler** [fuerthwiki/wiki#72]
Im von Doc Bendit eingestellten Foto "Stadtpark Luftaufnahme.jpg" war eine Warnmeldung drin wegen des Erstellungsdatums. Im Quelltext stand "/12", im Formular Januar 1970. Nach erneutem Abspeichern wurde das auch korrekt übernommen. Allerdings habe ich das Datum dann ganz rausgenommen, weil erstens in der Beschreibung steht "Aufnahme um 1962" und zweitens die Vegetation ganz und gar nicht nach Januar aussieht. Meine Vermutung: Nach Bot-Edits wurde in Bildern ohne Datum das Unix-Startdatum (01.01.1970) rudimentär übernommen. Kann also auch bei (womöglich vielen) anderen Bildern vorkommen.

Siehe Änderungshistorie zu
https://www.fuerthwiki.de/wiki/index.php/Datei:Stadtpark_Luftaufnahme.jpg

**Comment by docbendit** [comment]
Hier ist auch nachvollziehbar:
https://www.fuerthwiki.de/wiki/index.php/Datei_Diskussion:F%C3%BCrther_H%C3%B6fe_und_Gassen,_wie_sie_einst_waren_(28).jpg

Das Problem tritt anscheinend immer auf bei unvollständigen Datumsangaben und erneutem Abspeichern. Nicht gut!

**Comment by zonebattler** [comment]
Gemeinsamer Nenner beider Fälle ist der "Bot-Edit zur Entfernung der alten Datumsformate bei Bildern" von Mark!

**Comment by docbendit** [comment]
Klar, aber das löst es noch nicht aus. Erst das Abspeichern bei weiteren Bearbeitungen macht aus bei unvollständigen Datumsangaben wie z.B. 1900/12 oder 10/07 den Januar 1970. Soviel traue ich mich mittlerweile sicher zu sagen

**Comment by markmuzenhardt** [comment]
Es ist genau umgekehrt. Die Bot-Edits haben alle Datumsangaben völlig korrekt übersetzt. Der Fehler liegt in der PageForm-Extension, welche Datumsangaben Jahr/Monat falsch interpretiert. Richtig interpretiert werden Angaben mit Jahr/Monat/Tag oder nur Jahr. Es wurde letzte Woche schon ein Ticket im Repository des PageForms-Extension geöffnet durch mich, leider scheint das die Entwickler dort aber nicht zu scheren. Dann müssen wir es notfalls Forken und selber Fixen. Schöner Mist.

**Comment by markmuzenhardt** [comment]
Fehler beseitigt. PageForms wurde gepatcht mit zwei kleinen Workarounds, die nun Ein- wie Ausgangsseitig das Datumsformat "YYYY/MM/DD" oder "YYYY/MM" oder "YYYY" einheitlich verwenden.
