### ISSUE TITLE
Fehlerhafte Verlinkung bei semantischen Bildabfragen

### ISSUE THREAD

**Issue by docbendit** [fuerthwiki/wiki#73]
Bei der semantischen Bildersuche werden Verlinkungen im Beschreibungstext der Datei nicht mehr ausgeführt.
![bilderfehler](https://user-images.githubusercontent.com/32236081/30780528-f94fa782-a10c-11e7-80a2-4f867ba67b55.JPG)

**Comment by markmuzenhardt** [comment]
Siehe https://www.semantic-mediawiki.org/wiki/Help:$smwgLinksInValues#Legacy_behaviour. In LocaleSettings.php durch $smwgLinksInValues = SMW_LINV_OBFU; gefixt
