### ISSUE TITLE
Editor fehlt im Formular

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#74]
Wenn man das Formular {{Gasthaus}} verwendet - also den Artikel "mit Formluar bearbeiten" bearbeitet, dann kann man im Freitext zwar schreiben, aber der Editor etc. fehlt, um z.B. Verlinkungen, Markierung etc. machen zu können. Der Editor erscheint nur, wenn man auf der Seite "normal" auf bearbeiten geht - und somit das Formular umgeht.

**Comment by KasaFue** [comment]
Evtl. könnte man in dem Formular noch die Punkte "Bild" für das Kneipenlogo etc. mit aufnehmen - und eine Karte - dann könnte man die Kneipe gleich mittels Geokoordinaten auf der Karte anzeigen. Letzteres werden wir eh brauchen, wenn wir in der mobilen Fassung die Kneipen etc. in der Nähe anzeigen lassen wollen!

**Comment by KasaFue** [comment]
Achso. .. und bitte im Formular alle Punkte ausblenden, die nicht befüllt sind. Bei vielen Kneipen steht z.B. "Abbruch" im Formular-Text - was irgendwie fehlplaziert ist - siehe Süße Freiheit.

**Comment by markmuzenhardt** [comment]
Die Vorlage {{Gasthaus}} existiert nicht mehr. Stattdessen ist die Vorlage {{Gaststätte}} zu verwenden, die alle Probleme diesbezüglich beseitigt. Mein Job: Alle Gaststätten (vormals Gasthäuser) gleichzuziehen. Der Begriff wurde geändert, weil ein Gasthaus eine Gaststätte mit Übernachtungsmöglichkeit ist. Das trifft in Fürth auf die geringste Zahl von Einrichtungen dieser Art zu (falls es sowas überhaupt gibt). Eigentlich müsste man eine neue Vorlage {{Hotel}} schaffen, weil es eben kaum Gasthäuser in Fürth gibt.
