### ISSUE TITLE
ownCloud-Synchronisierung kaputt

### ISSUE THREAD

**Issue by zonebattler** [fuerthwiki/wiki#75]
Seit der Protokoll-Umstellung von http:// auf https:// synchronisiert der ownCloud-PC-Client das lokale Festplattenverzeichnis nicht mehr mit der Wolke. Das Anpassen des vorhandenen Profils ist nicht möglich, das Anlegen eines neuen leider auch nicht (siehe angehängte Fehlermeldungen).

![photo5337177489203636310](https://user-images.githubusercontent.com/31971014/30797082-ff60b472-a1d4-11e7-9cff-8cbb1b60a6ea.jpg)

![photo5336870978862557317](https://user-images.githubusercontent.com/31971014/30797090-097dc5a8-a1d5-11e7-8d87-25ad5b72dba9.jpg)

![photo5337177489203636311](https://user-images.githubusercontent.com/31971014/30797099-108ef20e-a1d5-11e7-827f-48b1b9ea9274.jpg)

![photo5337177489203636312](https://user-images.githubusercontent.com/31971014/30797108-14f0c700-a1d5-11e7-9fda-a2cee7c97b1e.jpg)

P.S.: Client ist auf aktueller Version. Sync-Versuche starten (incl. Dateinamenanlegung), aber transportiert wird nix mehr...

**Comment by zonebattler** [comment]
Ergoogelte Foren-Diskussionen zu diesem Fehler:

https://central.owncloud.org/t/desktop-client-fails-connecting-via-https/9592

Darin Verweis gefunden auf

https://doc.owncloud.com/server/10.0/admin_manual/configuration/server/harden_server.html?highlight=web%20server#use-https

**Comment by markmuzenhardt** [comment]
@zonebattler : Hast Du die Synchronisation schon mal komplett neu eingerichtet (also im OwnCloud-Client wirklich Eintrag rauslöschen und neu anlegen unter owncloud.fuertwiki.de?)

**Comment by zonebattler** [comment]
Nee, weil ich Angst hatte, daß dann gar nix mehr geht. Anderseits geht ja auch gar nix mehr, kann ich abends also noch probieren. Verspreche mir aber nix davon, wird wohl wieder auf die obigen Fehlermeldungen hinauslaufen...

**Comment by markmuzenhardt** [comment]
Vermutlich Versions- und/oder Zertifikats- Konflikt. Nachdem Ralph seinen Owncloud-Client mit der neuen URL neu eingerichtet hatte, funktionierte alles wieder.
