### ISSUE TITLE
Auto-Ergänzung im Suchfeld ist neuerdings case sensitive

### ISSUE THREAD

**Issue by zonebattler** [fuerthwiki/wiki#76]
Ich habe mit Verwunderung eben festgestellt, dass das Suchfeld im fürthwiki case sensitive ist. Wenn ich Kioski eintippe, wird nix gefunden, bei KIOSKI hingegen schon. Also ich rede von der automatischen Ergänzung im Suchfeld.

Adolf Schwammberger -> wird gefunden
adolf Schwammberger -> wird gefunden
adolf schwammberger -> wird NICHT gefunden und ergänzt!

Wunsch: Gleichwertigkeit von Groß- und Kleinschreibung (auch gemischt) im Suchfeld (wieder)herstellen!

**Comment by markmuzenhardt** [comment]
Nur der erste Buchstabe ist nicht case-sensitive. Alle weiteren Buchstaben schon, das war aber schon immer so. Ist ein wohl bekanntes Verhalten der MediaWiki-Software, welches durch uns selbst nicht mit vertretbarem Aufwand beseitigt werden kann. Da werden wir warten müssen, bis die MediaWiki-Software selbst eine bessere Lösung bietet.

**Comment by zonebattler** [comment]
OK. Komisch nur, daß mir das vorher nicht aufgefallen ist und seit dem KIOSKI ständig... ;-)
