### ISSUE TITLE
Integrierter Audio-Player funktioniert nicht mehr

### ISSUE THREAD

**Issue by zonebattler** [fuerthwiki/wiki#78]
Beispiel:

https://www.fuerthwiki.de/wiki/index.php/Stellwerk_Ottostraße#Zeitzeugenberichte

Play-Pfeile bleiben ausgegraut und sind nicht mehr bedienbar.

Ursache: vermutlich Vorlage

{{Audios zu diesem Ort}}

**Comment by mojoaxel** [comment]
vermutlich Vorlage:Audio_Galerie

**Comment by mojoaxel** [comment]
@markmuzenhardt Kannst du dir das mal anschauen? Ich bin da vorerst gescheitert. Irgendwie wird die richtige URL nicht durchgereicht.

**Comment by markmuzenhardt** [comment]
Gefixt. Https erlaubt keine Streams von http, das war das Problem.

**Comment by mojoaxel** [comment]
Problem tritt nach update auf 1.31 wieder auf.

**Comment by markmuzenhardt** [comment]
Problem gelöst - nur die Symptomatik war identisch. Fehler ist, dass das Abfrageverhalten von SemanticMediawiki in Version 3 anders ist als bisher. Vorlage {{Audio Galerie}} angepasst, jetzt funktioniert es wieder.
