### ISSUE TITLE
mp3-Dateihandling umständlich (wie vormals PDF)

### ISSUE THREAD

**Issue by zonebattler** [fuerthwiki/wiki#79]
Beispiel:

https://www.fuerthwiki.de/wiki/index.php/Gustavstraße#Bilder

Erste Datei: kein Thumbnail, abspielen erfordert drei Mausklicks (Thumbnail, Details, Dateiname). Vereinfachtes Handling wie neuerdings bei PDF-Dateien (ein Klick und los geht's) wäre wünschenswert.

Zu hinterfragen ist ferner, ob mp3-Dateien bei den Bildern richtig aufgehoben sind...

**Comment by markmuzenhardt** [comment]
Die mp3's haben bei den Bildern nichts verloren. Die haben eigene Vorlagen um sie in die Artikel einbinden zu können und damit wird für jede Audiodatei ein Player angezeigt. Bei "Bilder dieser Straße" wird jetzt deshalb zusätzlich auf die Kategorie:Bilder gefiltert, damit keine andersartigen Medien mehr in die Bildergalerie einziehen.
