### ISSUE TITLE
Verschiedene Bugs

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#83]
Es gibt immer noch ein paar Bugs, in der Ansicht von Tabellen und Info-Boxen, die mit einem gelben Dreieck mit Ausrufezeichen dargestellt werden bzw. In Tabellen mit {{}} dargestellt werden. Nachdem diese Probleme schon länger existieren, und ich den Eindruck habe, dass nach der Mobilmachung jetzt etwas die "Luft" raus ist - versuche ich es einfach nochmal mit einem neuen Ticket! 
![img_0129](https://user-images.githubusercontent.com/31972645/32979047-50125918-cc4e-11e7-950c-d5a7ff3a8a92.PNG)
![img_0130](https://user-images.githubusercontent.com/31972645/32979048-503adbb8-cc4e-11e7-9f44-68f1b7fbb39d.PNG)

**Comment by markmuzenhardt** [comment]
Leere Zeilen in Auszeichnungen ergeben sich, wenn man bei Personen noch die alte Form [[Auszeichnung::Bundesverdienstkreuz]] wählt. Die habe ich jetzt aber aus allen Personen-Artikeln rausgeschmissen, damit die Auszeichnungen nun ausschließlich über das Formular in die Datenbank aufgenommen werden.
