### ISSUE TITLE
Denkmalschutz-Link 

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#85]
Mir fällt gerade auf, dass der Link zur Landesdenkmaliste in der Info-Box nicht richtig angezeigt wird. Siehe Screenshot.
![screenshot gebaudelink](https://user-images.githubusercontent.com/31972645/33024980-e7f03240-ce0c-11e7-81d6-87dd04e396d3.JPG)

**Comment by markmuzenhardt** [comment]
Das Feld "Quelle" wird leider vom Plugin "SemanticExtraSpecialProperties" seit dem letzten Update als System-Feld reserviert, darum der Fehler. Lösung: In allen Vorlagen aller Artikel und Dateien das Wort |Quelle= durch |Quellangaben= ersetzt. Auch in den dazugehörigen Formularen. Hoffe ich habe alle erwischt.
