### ISSUE TITLE
Wunsch: "Mouse over Fenster"

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#87]
In der großen Wiki kann man seit kurzem feststellen, dass die innerhalb von Wiki verlinkten Wörter bereits in einer Voransicht angezeigt werden, sogar mit Bild. Das ist außnahmsweise mal ein cooles feature bei der Wiki - so dass sich mir die Frage aufgedrängt hat, ob wir das nicht auch übernehmen könnten? 

Bsp. 
![screeshot mouse over](https://user-images.githubusercontent.com/31972645/34413631-fd26acde-ebe4-11e7-9f50-34088905bc4f.jpg)

**Comment by markmuzenhardt** [comment]
Funktioniert seit eben
