### ISSUE TITLE
Open Streetmap Fenster in Vollbild öffnen

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#91]
Es kam von Usern der Wunsch auf, dass man in der Datenbox die angezeigte Open Streetmap öffenen können sollte - also in den Vollbildmodus zu wechseln. Die Anforderung erscheint sinnvoll, da man manchmal zur Orientierung einen größeren Bildschirm benötigt. Hierzu ist die Info-Box zu klein.

**Comment by mojoaxel** [comment]
Das sollte eigentlich relativ leicht umzusetzen sein.
Am einfachsten ist es wohl einfach die Vorlage anzupassen und einen Vollbild-Button in die Kartenansicht hinein zu hacken. Ich überleg mir mal was, wenn ich dazu komme.

**Comment by mojoaxel** [comment]
Man könnte folgendes tun:
In die Vorlage [Vorlage:Gebäude.Karte](https://www.fuerthwiki.de/wiki/index.php?title=Vorlage:Geb%C3%A4ude.Karte&action=edit) einen fullscreen button einbauen, der einen absoluten Link auf eine OpenStreetMap Karte enthällt. *lat* und *lon* sind an dieser Stelle vorhanden.

**Comment by KasaFue** [comment]
Größer und Kleiner ist da, das ist richtig - aber manchmal ist der Ausschnitt einfach zu klein, um sich orientieren zu können - deshalb wäre der Link auf die große Open Street Map Karte hilfreich und sinnvoll.

**Comment by KasaFue** [comment]
WOW ... super Lösung ... bitte gleich in dieser Qualität weiter machen mit den 36 noch offenen Fällen ;-)

**Comment by mojoaxel** [comment]
> bitte gleich in dieser Qualität weiter machen mit den 36 noch offenen Fällen ;-)

Sorry, hab das heute mal eingeschoben. Jetzt muss ich wieder anderweitig weiterarbeiten :-(
Ich habs im Hinterkopf und schau immer mal wieder, ob ich was verbessern kann. Wie immer versprech ich aber nix.

**Comment by KasaFue** [comment]
Alles klar... kein Problem! Aber für uns "Technikaußenstehende" wird hier die Liste gefühlt immer länger... von daher die postive Rückmeldung nach so kurzer Reaktionszeit ;-)
