### ISSUE TITLE
Straßenabkürzungen 

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#92]
Viele Menschen kürzen Straßennamen ab, sie schreiben z.B. Königstr. statt Königstraße oder Würzburgerstr. satt Würzburgerstraße. Wenn man nun Königstr. als Suchbegriff eingibt, dann findet FürthWiki nicht die Königstraße. Stattdessen erhält man die Frage, ob man die Königstr. als Artikel anlegen möchte? Klar, jetzt könnte man für jede Straße eine Weiterleitung anlegen. Aber - gibt es eine andere Lösung als eine Weiterleitung für dieses Problem?

**Comment by markmuzenhardt** [comment]
Ob das wirklich ein Problem ist? Solange die Leute Königstr ohne Punkt eingeben, findet die Suchmaschine auch was...

**Comment by KasaFue** [comment]
Ja, wir hatten erst kürzlich eine Rückmeldung von Extern, die das "Problem" beschrieben hat.

**Comment by mojoaxel** [comment]
Ich finde das Problem zwar interessant aber nicht dringend. Sucht man statt `Würzburgerstr`einfach nur nach `Würzburger` wird man fündig.

**Comment by markmuzenhardt** [comment]
Würde ich mal schließen, weil der Aufwand viel zu hoch ist.
