### ISSUE TITLE
Formulare werden manchmal nicht vollständig geladen

### ISSUE THREAD

**Issue by markmuzenhardt** [fuerthwiki/wiki#93]
Die PageForms extension macht speziell bei den Bildern (aber auch Personen) Probleme, weil das JavaScript des Formulars nicht komplett geladen wird. Teile des Formulars werden dadurch nicht richtig dargestellt oder funktionieren nicht richtig.
![probform](https://user-images.githubusercontent.com/6707417/36789784-03f6220e-1c93-11e8-8926-7f84fccb56dd.jpg)

In oben stehendem Bild ist erkennbar, was gemeint ist.

**Comment by markmuzenhardt** [comment]
Folgende Zeilen zu LocalSettings.php hinzugefügt:

# Loading PageForms complete and correct
$wgPageFormsCacheAutocompleteValues = true;
$wgPageFormsAutocompleteCacheTimeout = 60; // 1 minute (in seconds)

Timeout der PageForms schlägt viel zu früh zu, eine Minute kann ruhig noch verlängert werden...

**Comment by mojoaxel** [comment]
Ich glaube das Problem tritt immer noch auf.

**Comment by markmuzenhardt** [comment]
Done. Version 1.31 hat diesen Fehler nicht mehr.
