### ISSUE TITLE
Formatierung Einzelnachweise 

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#94]
Ich habe  bei der großen Wiki schon des öfteren gesehen, dass die Formatierung der Einzelnachweise in Spalten erfolgt, und nicht so wie bei uns als fortlaufender Text. Ich persönlich finde die Spalten-Lösung "sexyer" und optisch besser, als "unsere" Lösung. Ist das schwierig in der Umsetzung für uns - bzw. spricht was dagegen, es aus so zu machen?

![scr fussnoten](https://user-images.githubusercontent.com/31972645/36846906-d3c171b8-1d5c-11e8-94bf-2809bac8b090.JPG)

**Comment by markmuzenhardt** [comment]
Dagegen spricht nix. Wird beim nächsten Update wahrscheinlich sowiso automatisch so kommen (glaube nicht, dass dafür Programmieraufwand nötig wird).

**Comment by mojoaxel** [comment]
Das einzige, was dagegen sprechen könnte ist das responsive design. Man muss halt aufpassen, das z.B. auf Mobile oder Tablet nicht auch spalten benutzt werden.

**Comment by markmuzenhardt** [comment]
Done. Version 1.31 hat diese Option unter der Haube.
