### ISSUE TITLE
Anzeigen von Bildern erzwingen

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#95]
Wir öfters mal das Problem, dass mit der Semantisierung Bilder in Artikel nicht eingezeigt werden können, da sich der Artikelname nicht zur Beschreibung passt. Beispiel:

Wir haben eine Gaststätte mit dem Namen XY - die sich gleichzeitig im Gebäude AB befindet. Was nehme ich nun für die Beschreibung? Entweder {{Bilder dieses Gebäudes}} oder {{Bilder dieser Firma}} oder {{Bilder dieser Gaststätte}} usw usf. Wir haben Teilsweise Artikel, die beide Attribute unten stehen haben - und zum Teil völlig unterschiedliche Bilder anzeigen. 

Wie wäre es, wenn man in einem Artikel vorsagen könnte, welche Bilder gezeigt werden sollen? So könnte man in einem Gaststättenartikel z.B. schreiben {{Bilder:Straße AB}} - so dass hier jetzt die Bilder von dem Gebäude angezeigt werden. 

Bsp: Gaststätte Karo 11, die auch als Gaststätte Reuel bei uns einen Artikel hat, im Gebäude Karolinenstraße 11. Je nachdem in welchen Artikel in schaue, bekomme ich verschiedene Bilder angezeigt, aber nie alle gleichzeitig. 

Was meint Ihr dazu?

**Comment by KasaFue** [comment]
Noch ein Beispiel für eine Anwendungsmöglichkeit:
Mitglieder der NSDAP - hier haben wir einen Artikel, allerdings kann ich nicht mit dem Befehl {{Bilder dieser Partei}} arbeiten, das die Partei nicht "Mitglieder der NSDAP" heißt, sondern nur NSDAP. Hier wäre es jetzt praktisch, wenn ich sagen könnte, zeige mir auf dieser Seite - auch wenn sie anders heißt - alle Mitglieder einer Partei.

**Comment by markmuzenhardt** [comment]
Ok, jetzt existiert eine Vorlage "Bilder". Die wird so angesteuert:
{{Bilder|Partei|NSDAP}}. Also erstes Attribut ist der Name der Variable, die im Bild selbst als Bildattribut eingetragen ist. Das zweite Attribut ist der Wert. Reicht das?
