### ISSUE TITLE
Formular Fehler: HTML attribute value can not contain a list of values

### ISSUE THREAD

**Issue by mojoaxel** [fuerthwiki/wiki#97]
Bei einigen Formularen (z.B. Personen) follt es zu folgenden Fehler:
`HTML attribute value can not contain a list of values`

![image](https://user-images.githubusercontent.com/600565/37568015-aa46bca0-2acf-11e8-97d7-dbe8cfb0df34.png)

**Comment by mojoaxel** [comment]
Scheint ein Fehler im SemanticMediaWiki zu sein!? 
https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1473

**Comment by mojoaxel** [comment]
Das Problem tritt nur mit PageForms@4.3 auf.

**Comment by mojoaxel** [comment]
Wenn man allerdings das PageForms updated kommt es zu folgenden Fehler:
![photo5294395654975629591](https://user-images.githubusercontent.com/600565/39985369-bbb81446-575e-11e8-8c12-00b6b166eb5b.jpg)

**Comment by djflux** [comment]
Did this issue every get resolved? I am have the same issue and want to see if I should open a separate issue.

Here are my versions.

Product | Version
-- | --
MediaWiki | 1.31.0 (5cfc9ac)2018-06-13T10:34:24
PHP | 7.0.31 (apache2handler)
MariaDB | 5.5.60-MariaDB
ICU | 50.1.2
Elasticsearch | 5.6.11
Page Forms | 4.3.1 (0ba6735)2018-06-18T15:35:28

**Comment by mojoaxel** [comment]
@djflux We downgraded the PageForm plugin to 4.2.1. That fixed the problem for us. At least for now.

**Comment by markmuzenhardt** [comment]
PageForms 4.5.1 hat den Fehler offenbar nicht mehr
