### ISSUE TITLE
Wartungsliste stimmt nicht

### ISSUE THREAD

**Issue by KasaFue** [fuerthwiki/wiki#98]
Mir ist aufgefallen, dass einzelne Wartungslisten nicht stimmen. Bsp: Verwaiste Dateien

Hier wird behauptet, dass folgende Datei auf keine Seite verwendet wird: 
https://www.fuerthwiki.de/wiki/index.php/Datei:F%C3%BCrth_in_alten_Ansichten_(Buch)_Band_2.jpg 

Fakt ist aber, dass die Datei auf folgender Seite verwendet wird:
https://www.fuerthwiki.de/wiki/index.php/F%C3%BCrth_in_alten_Ansichten_(Buch) 

Durch "speichern" läßt sich manches lösen, auch wenn die Datei schon angezeigt wurde, in einigen Fällen geschieht trotzdem nichts - bzw. der Fehler bleibt bestehen:

https://www.fuerthwiki.de/wiki/index.php/Datei:DedenktafelBenario170914_Stellungnahme.jpg

Wie kommt es zu dieser "Fehlinterpretation"?

**Comment by markmuzenhardt** [comment]
Irgendwie sind alle genannten Beispiele nicht mehr in den "Verwaisten Dateien" aufgeführt. Alle Stichproben aus diesen Spezialseiten haben ergeben, dass die dort genannten Dateien wirklich verwaist sind. Kann es sein, dass die Bereinigung dieser Spezialseite nur einige Stunden bis Tage dauert und die Fehlinterpretationen daher kommen?

**Comment by markmuzenhardt** [comment]
Datenbank benötigt manchmal mehrere Stunden, um die Verwendung von Bildern in Artikeln abzubilden.
